# Generated by Django 4.2 on 2023-05-05 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_piloto', models.IntegerField(default=None)),
                ('moto', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Volta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_volta', models.IntegerField()),
                ('horario_largada', models.DateTimeField(blank=True, null=True)),
                ('horario_chegada', models.DateTimeField(blank=True, null=True)),
                ('tempo_volta', models.DateTimeField(blank=True, null=True)),
                ('tempo_acumulado', models.DateTimeField(blank=True, null=True)),
                ('numero_piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voltas', to='crono.piloto')),
            ],
            options={
                'unique_together': {('numero_piloto', 'numero_volta')},
            },
        ),
    ]
