# Generated by Django 4.1.5 on 2023-05-15 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_piloto', models.IntegerField(default=None)),
                ('moto', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_piloto', models.IntegerField(default=None)),
                ('moto', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('id_volta', models.IntegerField(blank=True, null=True)),
                ('horario_largada', models.TimeField(blank=True, null=True)),
                ('horario_chegada', models.TimeField(blank=True, null=True)),
                ('tempo_volta', models.DurationField(blank=True, null=True)),
                ('tempo_total', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registrar_Largada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_volta', models.IntegerField(blank=True, null=True)),
                ('horario_largada', models.TimeField(blank=True, null=True)),
                ('numero_piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='largadas', to='crono.piloto')),
            ],
        ),
        migrations.CreateModel(
            name='Registrar_Chegada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_volta', models.IntegerField(blank=True, null=True)),
                ('horario_chegada', models.TimeField(blank=True, null=True)),
                ('numero_piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chegadas', to='crono.piloto')),
            ],
        ),
    ]
