# Generated by Django 4.2 on 2023-05-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crono', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrar_Chegada',
            new_name='RegistrarChegada',
        ),
        migrations.RenameModel(
            old_name='Registrar_Largada',
            new_name='RegistrarLargada',
        ),
    ]
