# Generated by Django 4.2 on 2023-05-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crono', '0002_alter_piloto_nome_alter_piloto_numero_piloto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piloto',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='numero_piloto',
            field=models.IntegerField(default=None),
        ),
    ]
