# Generated by Django 4.2 on 2023-07-05 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crono', '0005_alter_resultados_id_volta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosCorrida',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('moto', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('id_volta', models.AutoField(primary_key=True, serialize=False)),
                ('horario_largada', models.TimeField(blank=True, null=True)),
                ('horario_chegada', models.TimeField(blank=True, null=True)),
                ('tempo_volta', models.DurationField(blank=True, null=True)),
                ('tempo_total', models.DurationField(blank=True, null=True)),
                ('numero_piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dadoscorridas', to='crono.piloto')),
            ],
        ),
    ]
